### ISSUE TITLE
Bug: Endpoint is different then documented

### ISSUE THREAD

**Issue by paavo** [bwaidelich/Wwwision.Renderlets.Provider#1]
The endpoint is documented as `__renderlets`, but configured as `__renderlet` @bwaidelich 

`private const URI_PATH_PREFIX = '__renderlet';`
`With this in place, the renderlet is exposed via HTTP on the endpoint `/__renderlets/some_renderlet`
`

https://github.com/bwaidelich/Wwwision.Renderlets.Provider/blob/main/README.md?plain=1#L23
https://github.com/bwaidelich/Wwwision.Renderlets.Provider/blob/bf595a106366936991eb4d07a45e325c58c38c44/Classes/Http/Middleware.php#L25

**Comment by bwaidelich** [comment]
Thanks, fixed
